/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal installs. It is checked in here
// so the repo remains type-aware before the first local install.
