import { type EmailOtpType } from "@supabase/supabase-js";
import { createServerClient } from "@supabase/ssr";
import { NextResponse, type NextRequest } from "next/server";
import { supabasePublishableKey, supabaseUrl } from "@/lib/supabase/config";

export const dynamic = "force-dynamic";

function safeRole(value: string | null) {
  return value === "instructor" ? "instructor" : "learner";
}

function safeNextPath(value: string | null, role: string) {
  const fallback = `/auth/verify?role=${role}`;
  if (!value || !value.startsWith("/") || value.startsWith("//")) {
    return fallback;
  }

  return value;
}

function loginRedirect(request: NextRequest, role: string, message: string) {
  const url = new URL(`/auth/login?role=${role}`, request.nextUrl.origin);
  url.searchParams.set("message", message);
  return NextResponse.redirect(url);
}

function createSupabaseCallbackClient(request: NextRequest, response: NextResponse) {
  if (!supabaseUrl || !supabasePublishableKey) {
    return null;
  }

  return createServerClient(supabaseUrl, supabasePublishableKey, {
    cookies: {
      getAll() {
        return request.cookies.getAll();
      },
      setAll(cookiesToSet) {
        cookiesToSet.forEach(({ name, value, options }) => {
          response.cookies.set(name, value, options);
        });
      }
    }
  });
}

function redirectWithAuthCookies(target: URL, response: NextResponse) {
  const redirectResponse = NextResponse.redirect(target);
  response.cookies.getAll().forEach((cookie) => {
    redirectResponse.cookies.set(cookie);
  });
  return redirectResponse;
}

export async function GET(request: NextRequest) {
  const role = safeRole(request.nextUrl.searchParams.get("role"));
  const nextPath = safeNextPath(request.nextUrl.searchParams.get("next"), role);
  const code = request.nextUrl.searchParams.get("code");
  const tokenHash = request.nextUrl.searchParams.get("token_hash");
  const otpType = request.nextUrl.searchParams.get("type");
  const errorDescription = request.nextUrl.searchParams.get("error_description") || request.nextUrl.searchParams.get("error");

  if (errorDescription) {
    return loginRedirect(request, role, errorDescription.replace(/\+/g, " "));
  }

  const response = NextResponse.next({
    request
  });
  const supabase = createSupabaseCallbackClient(request, response);

  if (!supabase) {
    return loginRedirect(request, role, "Supabase environment variables are not configured yet.");
  }

  if (code) {
    const { error } = await supabase.auth.exchangeCodeForSession(code);

    if (error) {
      const message = error.message.includes("code verifier")
        ? nextPath === "/auth/update-password"
          ? "This reset link was generated by the older same-device flow. Request a fresh password reset email and it will open the new-password page."
          : "This email link was generated by the older same-device login flow. Request a fresh LDA email link and it can be opened on any device."
        : error.message;
      return loginRedirect(request, role, message);
    }
  } else if (tokenHash && otpType) {
    const { error } = await supabase.auth.verifyOtp({
      token_hash: tokenHash,
      type: otpType as EmailOtpType
    });

    if (error) {
      return loginRedirect(request, role, error.message);
    }
  } else {
    return loginRedirect(request, role, "The email link is invalid or has expired. Request a fresh secure link.");
  }

  return redirectWithAuthCookies(new URL(nextPath, request.nextUrl.origin), response);
}
